"""init

Revision ID: ccf0c22c1198
Revises: 
Create Date: 2024-04-05 00:08:35.483711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccf0c22c1198'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('houses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('apartments_count', sa.Integer(), nullable=True),
    sa.Column('apartments_per_floor', sa.Integer(), nullable=True),
    sa.Column('entrances_count', sa.Integer(), nullable=True),
    sa.Column('floors_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_houses'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=63), nullable=True),
    sa.Column('last_name', sa.String(length=63), nullable=True),
    sa.Column('patronymic', sa.String(length=63), nullable=True),
    sa.Column('house_number', sa.Integer(), nullable=True),
    sa.Column('apartment_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['house_number'], ['houses.id'], name=op.f('fk_users_house_number_houses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_table('exclusion_polls',
    sa.Column('exclusion_candidate_id', sa.Integer(), nullable=False),
    sa.Column('votes', sa.Integer(), nullable=True),
    sa.Column('votes_required', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exclusion_candidate_id'], ['users.id'], name=op.f('fk_exclusion_polls_exclusion_candidate_id_users')),
    sa.PrimaryKeyConstraint('exclusion_candidate_id', name=op.f('pk_exclusion_polls'))
    )
    op.create_table('friend_pairs',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], name=op.f('fk_friend_pairs_friend_id_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_friend_pairs_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'friend_id', name=op.f('pk_friend_pairs'))
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_id', sa.Integer(), nullable=True),
    sa.Column('to_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['from_id'], ['users.id'], name=op.f('fk_messages_from_id_users')),
    sa.ForeignKeyConstraint(['to_id'], ['users.id'], name=op.f('fk_messages_to_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('friend_pairs')
    op.drop_table('exclusion_polls')
    op.drop_table('users')
    op.drop_table('houses')
    # ### end Alembic commands ###
